content:
  - name: masters
    label: Stortford Masters
    type: file
    path: masters/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: default.html }
      - { name: date, type: string, hidden: true, default: git Last Modified }
      - { name: body, label: Body, type: rich-text }
